### ISSUE TITLE
Can we improve speed of `argmin`/`min` by removing the `Result` part?

### ISSUE THREAD

**Issue by fzyzcjy** [rust-ndarray/ndarray-stats#85]
Hi thanks for the lib! When looking at code:

https://github.com/rust-ndarray/ndarray-stats/blob/b6628c6a1c143532673213c56d46da5fda80cbe8/src/quantile/mod.rs#L289-L304

I see some error handling. IMHO this may make the code much slower. Since I am only working with `f32` or `i32` or similar primitive numbers, can we remove such error handling? Thanks!

**Comment by nilgoyette** [comment]
You realize that this library exists for all kinds of programmers with different needs? Asking to remove something because **you** don't need it is not useful. In fact, you might need that "slow" error handling... it's checking for NaN which you might have because you're using `f32`.

By the way, you can use `argmin_skipnan`. It does the same thing but it ignore NaN.

**Comment by fzyzcjy** [comment]
Well I should say "adding a new function without this functionality to speed up". 

Anyway now I know `argmin_skipnan`, thanks!
